# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    ## Install dependencies
    - name: npm install
      run: |
        npm install

    ##Test
    - name: Run tests
      run: |
        CI=true npm run test

    ## Build and deploy
    - name: Build & deploy
      run: |
        npm run build
        firebase deploy --only hosting --token ${{ SECRETS.CI_FIREBASE_TOKEN }}
